gText_AppealNumWhichMoveWillBePlayed::
	.string "Ausdruck {STR_VAR_1}! Welche\n"
	.string "Attacke wird gezeigt?$"

gText_AppealNumButItCantParticipate::
	.string "Ausdruck {STR_VAR_1}! Aber es\n"
	.string "kann nicht teilnehmen!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} führt\n"
	.string "{STR_VAR_2} vor!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} beobachtet\n"
	.string "die anderen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "Soweit zur\n"
	.string "Ausdruckskraft!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Es wird sich der anderen\n"
	.string "PKMN mehr bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} kann danach\n"
	.string "keinen Ausdruck zeigen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Es kommt ein wenig\n"
	.string "zur Ruhe.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Die anderen PKMN nehmen\n"
	.string "es überhaupt nicht wahr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Es ist sich der anderen\n"
	.string "PKMN kaum bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Es kümmert sich nicht\n"
	.string "mehr viel um andere PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu blenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Der JUROR schaut\n"
	.string "{STR_VAR_1} nicht mehr an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Es versucht, d. folgenden\n"
	.string "PKMN zu entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} wird\n"
	.string "nervös.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Dieser Ausdruck soll die\n"
	.string "anderen PKMN entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Es verhöhnt die\n"
	.string "besseren PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} findet zu\n"
	.string "seiner Form zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Es versucht, die besseren\n"
	.string "PKMN zu beeindrucken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{STR_VAR_1} an der Spitze\n"
	.string "engagiert sich noch mehr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Das bisher unauffällige\n"
	.string "{STR_VAR_1} gibt alles.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Es strengt sich genauso\n"
	.string "an wie die PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam nicht gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Es strengt sich an wie die\n"
	.string "vorangegangenen PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war absolut mies.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Der gleiche Typ wie das\n"
	.string "vorhergehende PKMN. Gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Nicht der gleiche Typ wie\n"
	.string "das vorherige PKMN - gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Es ist viel besser als die\n"
	.string "vorhergehenden PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Es war nicht so gut wie\n"
	.string "das PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Die Kondition von\n"
	.string "{STR_VAR_1} stieg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Status von {STR_VAR_1}:\n"
	.string "Bewirkt guten Ausdruck!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Es steigt in der Reihen-\n"
	.string "folge auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Es fällt in der Reihen-\n"
	.string "folge zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Es bringt die Reihenfolge\n"
	.string "durcheinander.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Der JUROR betrachtet\n"
	.string "{STR_VAR_1} interessiert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam sehr gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "Die Combo der Ausdrücke\n"
	.string "kam exzellent an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} gelingt es,\n"
	.string "den Blick abzuwenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} wandte den\n"
	.string "Blick erfolgreich ab.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} lässt sich\n"
	.string "davon nicht ablenken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} wurde etwas\n"
	.string "unruhig.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} blickt\n"
	.string "irritiert zu Boden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} dreht sich\n"
	.string "irritiert um.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} kann einen \n"
	.string "Laut nicht unterdrücken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} kann nicht\n"
	.string "anders und springt auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} ist so irri-\n"
	.string "tiert, dass es stolpert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} ist zu nervös,\n"
	.string "um etwas vorzuführen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "Es hatte keinen Erfolg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Es konnte keine\n"
	.string "Nervosität erzeugen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Aber es konnte niemanden\n"
	.string "nervös machen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "Es wurde ignoriert…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "Es konnte seinen Aus-\n"
	.string "druck nicht verstärken…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Schwacher Ausdruck we-\n"
	.string "gen schlechter Kondition.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} blieb\n"
	.string "unbeeindruckt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} enttäuscht\n"
	.string "durch Wiederholung.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war nicht gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1} begeistert\n"
	.string "Publikum mit {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} setzt in der \n"
	.string "folgenden Runde aus.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "Die Aufmerksamkeit des\n"
	.string "Publikums liegt auf ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "Das Publikum beobachtet\n"
	.string "weiterhin {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} von\n"
	.string "{STR_VAR_1} sah keiner.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "Scheu$"

gText_Contest_Anxiety::
	.string "Besorgnis$"

gText_Contest_Laziness::
	.string "Faulheit$"

gText_Contest_Hesitancy::
	.string "Zögern$"

gText_Contest_Fear::
	.string "Furcht$"
